[ZoneTransfer]
ZoneId=3
ReferrerUrl=C:\Users\AlvinandRaynes\Videos\Educationals\Docker and Kubernetes The Complete Guide\[TutsNode.com] - Docker and Kubernetes\11 Multi-Container Deployments to AWS\183 182-finished.zip
